# Generated by Django 2.2.4 on 2020-08-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_productvariation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'unique_together': {('name', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VariationName')),
            ],
            options={
                'unique_together': {('variation', 'value')},
            },
        ),
    ]
