# Generated by Django 2.2.4 on 2020-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productvariation_variationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationname',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
