# Generated by Django 2.2.4 on 2020-08-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200805_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueName', models.CharField(max_length=100)),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Option')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='SkuValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Option')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('skuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductSku')),
                ('valueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OptionValue')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='variantvalue',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='VariantValue',
        ),
    ]
