# Generated by Django 2.2.4 on 2020-08-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200806_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VariationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'unique_together': {('name', 'product')},
            },
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='optionId',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='skuvalue',
            name='optionId',
        ),
        migrations.RemoveField(
            model_name='skuvalue',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='skuvalue',
            name='skuId',
        ),
        migrations.RemoveField(
            model_name='skuvalue',
            name='valueId',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.DeleteModel(
            name='ProductSku',
        ),
        migrations.DeleteModel(
            name='SkuValue',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VariationName'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('variation', 'value')},
        ),
    ]
