# Generated by Django 2.2.4 on 2020-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200806_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variationName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
