# Generated by Django 2.2.4 on 2020-08-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200807_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Variation'),
        ),
    ]
