# Generated by Django 2.2.4 on 2020-08-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200807_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationCategory', models.CharField(max_length=100)),
                ('variationValue', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='sizevar',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
        migrations.AlterField(
            model_name='ordeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinalVariation'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinalVariation'),
        ),
        migrations.DeleteModel(
            name='ColorVar',
        ),
        migrations.DeleteModel(
            name='SizeVar',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.AddField(
            model_name='finalvariation',
            name='variationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FinalVariation.variationId+', to='core.MiddleVariation'),
        ),
        migrations.AddField(
            model_name='finalvariation',
            name='variations',
            field=models.ManyToManyField(to='core.MiddleVariation'),
        ),
    ]
