# Generated by Django 2.2.4 on 2020-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200809_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalvariation',
            name='variationId',
        ),
        migrations.RemoveField(
            model_name='middlevariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='finalvariation',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
