# Generated by Django 2.2.4 on 2020-08-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_item_has_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalvariation',
            name='variations',
            field=models.ManyToManyField(blank=True, to='core.MiddleVariation'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('media_attach', models.FileField(upload_to='')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
