# Generated by Django 2.2.4 on 2020-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200923_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlevariation',
            name='variationCategory',
            field=models.CharField(default='Size', help_text='Ex: Color, Size', max_length=100),
        ),
    ]
