# Generated by Django 2.2.4 on 2020-09-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Bangle', 'Bangle'), ('Chain', 'Link, Chain'), ('Stud', 'Stud'), ('Tops', 'Ear-Ring, Tops'), ('Brooch', 'Brooch'), ('Necklace', 'Necklace')], max_length=1),
        ),
    ]
