# Generated by Django 2.2.4 on 2020-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20201011_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
