# Generated by Django 2.2.4 on 2020-10-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20201012_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_details_saved',
            field=models.BooleanField(default=False),
        ),
    ]
