# Generated by Django 2.2.4 on 2020-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_profile_bank_details_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
