# Generated by Django 2.2.4 on 2020-10-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20201014_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subcription',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_booster': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subcription'),
        ),
    ]
