# Generated by Django 2.2.4 on 2020-10-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_orderitem_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='booster_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subs_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
