# Generated by Django 2.2.14 on 2020-10-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20201024_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='received',
        ),
    ]
