# Generated by Django 2.2.4 on 2020-10-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20201025_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
