# Generated by Django 2.2.14 on 2020-07-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ordeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wishitem',
            field=models.ManyToManyField(to='core.OrdeItem'),
        ),
    ]
