# Generated by Django 2.2.4 on 2020-08-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productvariation_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
