# Generated by Django 2.2.4 on 2020-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_variationname_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationname',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
