# Generated by Django 2.2.4 on 2020-08-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200805_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productVariantName', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Variant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variationname',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variationname',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='VariationName',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='productVariantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='valueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VariantValue'),
        ),
    ]
