# Generated by Django 2.2.4 on 2020-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200815_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='media_attach',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
