# Generated by Django 2.2.4 on 2020-08-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200819_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Check If you need to upload a video'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='media_attach',
            field=models.FileField(blank=True, help_text='Click to upload video', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finalvariation',
            name='price',
            field=models.FloatField(help_text='Including discount if available', null=True),
        ),
        migrations.AlterField(
            model_name='finalvariation',
            name='variationName',
            field=models.CharField(help_text='Enter the variation name in the following manner\nProductName-vartions\n\tEx: Car-Red-SUV', max_length=100),
        ),
        migrations.AlterField(
            model_name='finalvariation',
            name='variations',
            field=models.ManyToManyField(blank=True, help_text='Select the required options. Add variations category by clicking "+" sign', to='core.MiddleVariation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='middlevariation',
            name='productId',
            field=models.ForeignKey(help_text='Select your Product', on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
        migrations.AlterField(
            model_name='middlevariation',
            name='variationCategory',
            field=models.CharField(help_text='Ex: Color, Size', max_length=100),
        ),
        migrations.AlterField(
            model_name='middlevariation',
            name='variationValue',
            field=models.CharField(help_text='Ex: Red, XL', max_length=100),
        ),
    ]
