# Generated by Django 2.2.4 on 2020-09-23 12:51

import core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200819_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='media_attach',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
