# Generated by Django 2.2.4 on 2020-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200923_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Bangle', 'Bangle'), ('Chain', 'Link, Chain'), ('Stud', 'Stud'), ('Tops', 'Ear-Ring, Tops'), ('Brooch', 'Brooch'), ('Necklace', 'Necklace')], max_length=50),
        ),
    ]
