# Generated by Django 2.2.4 on 2020-09-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200924_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cgst_tax_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sgst_tax_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cgst_tax_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sgst_tax_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxName', models.CharField(max_length=50)),
                ('ValueType', models.CharField(choices=[('In Rupees', 'Rs'), ('In Percentage', 'Percent')], max_length=50)),
                ('TaxValue', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
