# Generated by Django 2.2.4 on 2020-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200926_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
