# Generated by Django 2.2.4 on 2020-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200926_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
