# Generated by Django 2.2.4 on 2020-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200926_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
