# Generated by Django 2.2 on 2020-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200926_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phoneNo',
        ),
        migrations.AddField(
            model_name='customer',
            name='alt_contact_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
