# Generated by Django 2.2.4 on 2020-10-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('entries', models.IntegerField(blank=True, null=True)),
                ('is_booster', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='days_valid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='entries_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='booster',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Subcription'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subcription'),
        ),
    ]
