# Generated by Django 2.2.4 on 2020-10-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_subcription_has_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcription',
            old_name='has_priority',
            new_name='has_priority_support',
        ),
    ]
