# Generated by Django 2.2.4 on 2020-10-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20201016_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='booster_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subs_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
