# Generated by Django 2.2.4 on 2020-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_item_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
