# Generated by Django 2.2.14 on 2020-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
