# Generated by Django 2.2.14 on 2020-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_comment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
