# Generated by Django 2.2.14 on 2020-10-24 14:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20201018_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='comment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment Id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Shipping Details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Id'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='core.BillingAddress', verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Id'),
        ),
    ]
