# Generated by Django 2.2.4 on 2020-10-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_orderitem_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='being_delivered',
            field=models.BooleanField(default=False, verbose_name='Order Delivered'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_placed',
            field=models.BooleanField(default=False, verbose_name='Order Accepted'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_rejected',
            field=models.BooleanField(default=False, verbose_name='Order Cancelled'),
        ),
    ]
